// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3lvypFqd7NZmTnHehESR34dRU_eTsm8U',
    appId: '1:543158707149:web:bf05a414e34f4b4545da84',
    messagingSenderId: '543158707149',
    projectId: 'portfolioamn-2b017',
    authDomain: 'portfolioamn-2b017.firebaseapp.com',
    storageBucket: 'portfolioamn-2b017.appspot.com',
    measurementId: 'G-ZZ9YQ7VD29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASokw0bqknLW59SqCcKeJsXiljV4lEjok',
    appId: '1:543158707149:android:71593522b586e7be45da84',
    messagingSenderId: '543158707149',
    projectId: 'portfolioamn-2b017',
    storageBucket: 'portfolioamn-2b017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhrRgVPkBtQf1-Jg201_8112w8FPd2q7s',
    appId: '1:543158707149:ios:a030a6d3eb874edb45da84',
    messagingSenderId: '543158707149',
    projectId: 'portfolioamn-2b017',
    storageBucket: 'portfolioamn-2b017.appspot.com',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhrRgVPkBtQf1-Jg201_8112w8FPd2q7s',
    appId: '1:543158707149:ios:a030a6d3eb874edb45da84',
    messagingSenderId: '543158707149',
    projectId: 'portfolioamn-2b017',
    storageBucket: 'portfolioamn-2b017.appspot.com',
    iosBundleId: 'com.example.myPortfolio',
  );
}
